import { HttpStatus } from '@nestjs/common';
import { CATALOG_ERROR_CODE, type CatalogErrorCode } from '../domain/catalog.repository';

/** Maps stable Catalog business semantics at the HTTP boundary; messages never participate. */
export function mapCatalogErrorToHttpStatus(code: CatalogErrorCode): HttpStatus {
  switch (code) {
    case CATALOG_ERROR_CODE.CATEGORY_NOT_FOUND:
      return HttpStatus.NOT_FOUND;

    case CATALOG_ERROR_CODE.CATEGORY_CODE_ALREADY_EXISTS:
    case CATALOG_ERROR_CODE.CATEGORY_INACTIVE:
    case CATALOG_ERROR_CODE.PRODUCT_SLUG_ALREADY_EXISTS:
    case CATALOG_ERROR_CODE.PRODUCT_CODE_ALREADY_EXISTS:
    case CATALOG_ERROR_CODE.PRODUCT_VARIANT_COMBINATION_DUPLICATE:
    case CATALOG_ERROR_CODE.RENTAL_RATE_DURATION_DUPLICATE:
    case CATALOG_ERROR_CODE.PRODUCT_ACTIVE_RENTAL:
    case CATALOG_ERROR_CODE.INVENTORY_SKU_ALREADY_EXISTS:
    case CATALOG_ERROR_CODE.INVENTORY_BARCODE_ALREADY_EXISTS:
    case CATALOG_ERROR_CODE.INVENTORY_STATUS_MISMATCH:
    case CATALOG_ERROR_CODE.INVENTORY_ACTIVE_ALLOCATION:
    case CATALOG_ERROR_CODE.INVENTORY_OCCUPIED_TRANSITION:
      return HttpStatus.CONFLICT;

    case CATALOG_ERROR_CODE.CATEGORY_INVALID_PARENT:
    case CATALOG_ERROR_CODE.PRODUCT_SLUG_INVALID:
    case CATALOG_ERROR_CODE.PRODUCT_MULTIPLE_PRIMARY_MEDIA:
    case CATALOG_ERROR_CODE.SIZE_NOT_IN_SHOP:
    case CATALOG_ERROR_CODE.COLOR_NOT_IN_SHOP:
    case CATALOG_ERROR_CODE.INVENTORY_LOCATION_INVALID:
    case CATALOG_ERROR_CODE.INVENTORY_MANUAL_OCCUPANCY_TRANSITION:
    case CATALOG_ERROR_CODE.INVENTORY_STATUS_NO_OP:
    case CATALOG_ERROR_CODE.INVENTORY_STATUS_TRANSITION_INVALID:
    case CATALOG_ERROR_CODE.INVENTORY_STATUS_REASON_REQUIRED:
      return HttpStatus.BAD_REQUEST;
  }
}
