export const PERMISSIONS = {
  DASHBOARD_VIEW: 'dashboard.view',
  CUSTOMERS_VIEW: 'customers.view',
  CUSTOMERS_CREATE: 'customers.create',
  CUSTOMERS_UPDATE: 'customers.update',
  CATALOG_VIEW: 'catalog.view',
  CATALOG_MANAGE: 'catalog.manage',
  INVENTORY_VIEW: 'inventory.view',
  INVENTORY_MANAGE: 'inventory.manage',
  RENTALS_VIEW: 'rentals.view',
  RENTALS_CREATE: 'rentals.create',
  RENTALS_UPDATE: 'rentals.update',
  RENTALS_CONFIRM: 'rentals.confirm',
  RENTALS_RETURN: 'rentals.return',
  RENTALS_SETTLE: 'rentals.settle',
  RENTALS_CANCEL: 'rentals.cancel',
  PAYMENTS_VIEW: 'payments.view',
  PAYMENTS_CREATE: 'payments.create',
  FINANCE_VIEW: 'finance.view',
  FINANCE_MANAGE: 'finance.manage',
  REPORTS_VIEW: 'reports.view',
  DELIVERIES_VIEW: 'deliveries.view',
  DELIVERIES_MANAGE: 'deliveries.manage',
  REMINDERS_VIEW: 'reminders.view',
  REMINDERS_MANAGE: 'reminders.manage',
  SETTINGS_VIEW: 'settings.view',
  SETTINGS_MANAGE: 'settings.manage',
  MEMBERS_MANAGE: 'members.manage',
  AUDIT_VIEW: 'audit.view',
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
