import { ApplicationError, type ApplicationErrorKind } from '@common/errors/application-error';

export const CATALOG_ERROR_CODE = {
  CATEGORY_CODE_ALREADY_EXISTS: 'CATEGORY_CODE_ALREADY_EXISTS',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_INACTIVE: 'CATEGORY_INACTIVE',
  CATEGORY_INVALID_PARENT: 'CATEGORY_INVALID_PARENT',
  PRODUCT_SLUG_ALREADY_EXISTS: 'PRODUCT_SLUG_ALREADY_EXISTS',
  PRODUCT_SLUG_INVALID: 'PRODUCT_SLUG_INVALID',
  PRODUCT_CODE_ALREADY_EXISTS: 'PRODUCT_CODE_ALREADY_EXISTS',
  PRODUCT_VARIANT_COMBINATION_DUPLICATE: 'PRODUCT_VARIANT_COMBINATION_DUPLICATE',
  PRODUCT_VARIANT_CODE_ALREADY_EXISTS: 'PRODUCT_VARIANT_CODE_ALREADY_EXISTS',
  PRODUCT_VARIANT_NOT_FOUND: 'PRODUCT_VARIANT_NOT_FOUND',
  PRODUCT_VARIANT_IN_USE: 'PRODUCT_VARIANT_IN_USE',
  PRODUCT_VARIANT_ARCHIVED: 'PRODUCT_VARIANT_ARCHIVED',
  RENTAL_RATE_DURATION_DUPLICATE: 'RENTAL_RATE_DURATION_DUPLICATE',
  PRODUCT_MULTIPLE_PRIMARY_MEDIA: 'PRODUCT_MULTIPLE_PRIMARY_MEDIA',
  PRODUCT_ACTIVE_RENTAL: 'PRODUCT_ACTIVE_RENTAL',
  COLOR_NOT_FOUND: 'COLOR_NOT_FOUND',
  COLOR_CODE_ALREADY_EXISTS: 'COLOR_CODE_ALREADY_EXISTS',
  COLOR_IN_USE: 'COLOR_IN_USE',
  COLOR_INACTIVE: 'COLOR_INACTIVE',
  COLOR_CODE_INVALID: 'COLOR_CODE_INVALID',
  COLOR_NAME_INVALID: 'COLOR_NAME_INVALID',
  COLOR_HEX_INVALID: 'COLOR_HEX_INVALID',
  SIZE_NOT_FOUND: 'SIZE_NOT_FOUND',
  SIZE_CODE_ALREADY_EXISTS: 'SIZE_CODE_ALREADY_EXISTS',
  SIZE_IN_USE: 'SIZE_IN_USE',
  SIZE_INACTIVE: 'SIZE_INACTIVE',
  SIZE_CODE_INVALID: 'SIZE_CODE_INVALID',
  SIZE_NAME_INVALID: 'SIZE_NAME_INVALID',
  SIZE_SORT_ORDER_INVALID: 'SIZE_SORT_ORDER_INVALID',
  INVENTORY_LOCATION_INVALID: 'INVENTORY_LOCATION_INVALID',
  INVENTORY_SKU_ALREADY_EXISTS: 'INVENTORY_SKU_ALREADY_EXISTS',
  INVENTORY_BARCODE_ALREADY_EXISTS: 'INVENTORY_BARCODE_ALREADY_EXISTS',
  INVENTORY_STATUS_MISMATCH: 'INVENTORY_STATUS_MISMATCH',
  INVENTORY_ACTIVE_ALLOCATION: 'INVENTORY_ACTIVE_ALLOCATION',
  INVENTORY_MANUAL_OCCUPANCY_TRANSITION: 'INVENTORY_MANUAL_OCCUPANCY_TRANSITION',
  INVENTORY_OCCUPIED_TRANSITION: 'INVENTORY_OCCUPIED_TRANSITION',
  INVENTORY_STATUS_NO_OP: 'INVENTORY_STATUS_NO_OP',
  INVENTORY_STATUS_TRANSITION_INVALID: 'INVENTORY_STATUS_TRANSITION_INVALID',
  INVENTORY_STATUS_REASON_REQUIRED: 'INVENTORY_STATUS_REASON_REQUIRED',
} as const;

export type CatalogErrorCode = (typeof CATALOG_ERROR_CODE)[keyof typeof CATALOG_ERROR_CODE];

const CATALOG_ERROR_KIND: Readonly<Record<CatalogErrorCode, ApplicationErrorKind>> = {
  CATEGORY_CODE_ALREADY_EXISTS: 'CONFLICT',
  CATEGORY_NOT_FOUND: 'NOT_FOUND',
  CATEGORY_INACTIVE: 'CONFLICT',
  CATEGORY_INVALID_PARENT: 'VALIDATION',
  PRODUCT_SLUG_ALREADY_EXISTS: 'CONFLICT',
  PRODUCT_SLUG_INVALID: 'VALIDATION',
  PRODUCT_CODE_ALREADY_EXISTS: 'CONFLICT',
  PRODUCT_VARIANT_COMBINATION_DUPLICATE: 'CONFLICT',
  PRODUCT_VARIANT_CODE_ALREADY_EXISTS: 'CONFLICT',
  PRODUCT_VARIANT_NOT_FOUND: 'NOT_FOUND',
  PRODUCT_VARIANT_IN_USE: 'CONFLICT',
  PRODUCT_VARIANT_ARCHIVED: 'CONFLICT',
  RENTAL_RATE_DURATION_DUPLICATE: 'CONFLICT',
  PRODUCT_MULTIPLE_PRIMARY_MEDIA: 'VALIDATION',
  PRODUCT_ACTIVE_RENTAL: 'CONFLICT',
  COLOR_NOT_FOUND: 'NOT_FOUND',
  COLOR_CODE_ALREADY_EXISTS: 'CONFLICT',
  COLOR_IN_USE: 'CONFLICT',
  COLOR_INACTIVE: 'CONFLICT',
  COLOR_CODE_INVALID: 'VALIDATION',
  COLOR_NAME_INVALID: 'VALIDATION',
  COLOR_HEX_INVALID: 'VALIDATION',
  SIZE_NOT_FOUND: 'NOT_FOUND',
  SIZE_CODE_ALREADY_EXISTS: 'CONFLICT',
  SIZE_IN_USE: 'CONFLICT',
  SIZE_INACTIVE: 'CONFLICT',
  SIZE_CODE_INVALID: 'VALIDATION',
  SIZE_NAME_INVALID: 'VALIDATION',
  SIZE_SORT_ORDER_INVALID: 'VALIDATION',
  INVENTORY_LOCATION_INVALID: 'VALIDATION',
  INVENTORY_SKU_ALREADY_EXISTS: 'CONFLICT',
  INVENTORY_BARCODE_ALREADY_EXISTS: 'CONFLICT',
  INVENTORY_STATUS_MISMATCH: 'CONFLICT',
  INVENTORY_ACTIVE_ALLOCATION: 'CONFLICT',
  INVENTORY_MANUAL_OCCUPANCY_TRANSITION: 'VALIDATION',
  INVENTORY_OCCUPIED_TRANSITION: 'CONFLICT',
  INVENTORY_STATUS_NO_OP: 'VALIDATION',
  INVENTORY_STATUS_TRANSITION_INVALID: 'VALIDATION',
  INVENTORY_STATUS_REASON_REQUIRED: 'VALIDATION',
};

export class CatalogInvariantError extends ApplicationError {
  readonly kind: ApplicationErrorKind;

  constructor(
    override readonly code: CatalogErrorCode,
    message: string,
  ) {
    super(message, code);
    this.kind = CATALOG_ERROR_KIND[code];
  }
}

export class CatalogCategoryCodeAlreadyExistsError extends CatalogInvariantError {
  constructor() {
    super(CATALOG_ERROR_CODE.CATEGORY_CODE_ALREADY_EXISTS, 'Mã danh mục đã tồn tại.');
  }
}

export class CatalogCategoryError extends CatalogInvariantError {
  constructor(
    code:
      | typeof CATALOG_ERROR_CODE.CATEGORY_NOT_FOUND
      | typeof CATALOG_ERROR_CODE.CATEGORY_INACTIVE,
  ) {
    super(
      code,
      code === 'CATEGORY_INACTIVE' ? 'Danh mục đã ngừng hoạt động.' : 'Không tìm thấy danh mục.',
    );
  }
}

export class CatalogCategoryInvalidParentError extends CatalogInvariantError {
  constructor(message = 'Danh mục không thể chọn chính nó làm danh mục cha.') {
    super(CATALOG_ERROR_CODE.CATEGORY_INVALID_PARENT, message);
  }
}

export class CatalogProductSlugAlreadyExistsError extends CatalogInvariantError {
  constructor() {
    super(
      CATALOG_ERROR_CODE.PRODUCT_SLUG_ALREADY_EXISTS,
      'Slug sản phẩm đã tồn tại trong cửa hàng.',
    );
  }
}

type CatalogColorErrorCode =
  | typeof CATALOG_ERROR_CODE.COLOR_NOT_FOUND
  | typeof CATALOG_ERROR_CODE.COLOR_CODE_ALREADY_EXISTS
  | typeof CATALOG_ERROR_CODE.COLOR_IN_USE
  | typeof CATALOG_ERROR_CODE.COLOR_INACTIVE
  | typeof CATALOG_ERROR_CODE.COLOR_CODE_INVALID
  | typeof CATALOG_ERROR_CODE.COLOR_NAME_INVALID
  | typeof CATALOG_ERROR_CODE.COLOR_HEX_INVALID;

const COLOR_ERROR_MESSAGES: Record<CatalogColorErrorCode, string> = {
  COLOR_NOT_FOUND: 'Không tìm thấy màu sắc.',
  COLOR_CODE_ALREADY_EXISTS: 'Mã màu đã tồn tại trong cửa hàng.',
  COLOR_IN_USE: 'Màu sắc đang được phân loại sản phẩm sử dụng.',
  COLOR_INACTIVE: 'Màu sắc đã ngừng hoạt động.',
  COLOR_CODE_INVALID: 'Mã màu chỉ được chứa chữ in hoa, chữ số và dấu gạch dưới; tối đa 50 ký tự.',
  COLOR_NAME_INVALID: 'Tên màu không được để trống và tối đa 100 ký tự.',
  COLOR_HEX_INVALID: 'Mã màu phải có định dạng #RRGGBB.',
};

export class CatalogColorError extends CatalogInvariantError {
  constructor(code: CatalogColorErrorCode) {
    super(code, COLOR_ERROR_MESSAGES[code]);
  }
}

type CatalogSizeErrorCode =
  | typeof CATALOG_ERROR_CODE.SIZE_NOT_FOUND
  | typeof CATALOG_ERROR_CODE.SIZE_CODE_ALREADY_EXISTS
  | typeof CATALOG_ERROR_CODE.SIZE_IN_USE
  | typeof CATALOG_ERROR_CODE.SIZE_INACTIVE
  | typeof CATALOG_ERROR_CODE.SIZE_CODE_INVALID
  | typeof CATALOG_ERROR_CODE.SIZE_NAME_INVALID
  | typeof CATALOG_ERROR_CODE.SIZE_SORT_ORDER_INVALID;

const SIZE_ERROR_MESSAGES: Record<CatalogSizeErrorCode, string> = {
  SIZE_NOT_FOUND: 'Không tìm thấy kích thước.',
  SIZE_CODE_ALREADY_EXISTS: 'Mã kích thước đã tồn tại trong cửa hàng.',
  SIZE_IN_USE: 'Kích thước đang được phân loại sản phẩm sử dụng.',
  SIZE_INACTIVE: 'Kích thước đã ngừng hoạt động.',
  SIZE_CODE_INVALID:
    'Mã kích thước chỉ được chứa chữ in hoa, chữ số và dấu gạch dưới; tối đa 50 ký tự.',
  SIZE_NAME_INVALID: 'Tên kích thước không được để trống và tối đa 100 ký tự.',
  SIZE_SORT_ORDER_INVALID: 'Thứ tự hiển thị phải là số nguyên không âm.',
};

export class CatalogSizeError extends CatalogInvariantError {
  constructor(code: CatalogSizeErrorCode) {
    super(code, SIZE_ERROR_MESSAGES[code]);
  }
}
